export const ActionTypes = {
        USER_LOGGED_IN: "USER_LOGGED_IN",
        USER_LOGGED_OUT: "USER_LOGGED_OUT",

        DESCENDING_SORT: "DESCENDING_SORT",
        ASCENDING_SORT : "ASCENDING_SORT"
}